const nextFontMock =
  require.resolve('next/dist/build/jest/__mocks__/nextFontMock.js')

const esmPackages = [
  'unified',
  'bail',
  'trough',
  'is-plain-obj',
  'devlop',
  'vfile',
  'vfile-message',
  'vfile-location',
  'vfile-matter',
  'remark-parse',
  'remark-rehype',
  'remark-stringify',
  'rehype-parse',
  'unist-util-visit',
  'unist-util-visit-parents',
  'unist-util-is',
  'unist-util-position',
  'unist-util-stringify-position',
  'unist-util-remove',
  'mdast-util-from-markdown',
  'mdast-util-to-hast',
  'mdast-util-to-markdown',
  'mdast-util-to-string',
  'mdast-util-phrasing',
  'mdast-util-mdx',
  'mdast-util-mdx-expression',
  'mdast-util-mdx-jsx',
  'mdast-util-mdxjs-esm',
  'hast-util-to-string',
  'hast-util-whitespace',
  'hast-util-from-html',
  'hast-util-from-parse5',
  'hast-util-parse-selector',
  'hast-util-to-estree',
  'hast-util-to-html',
  'hast-util-to-jsx-runtime',
  'micromark',
  'micromark-core-commonmark',
  'micromark-extension-mdx-expression',
  'micromark-extension-mdx-jsx',
  'micromark-extension-mdx-md',
  'micromark-extension-mdxjs',
  'micromark-extension-mdxjs-esm',
  'micromark-factory-destination',
  'micromark-factory-label',
  'micromark-factory-mdx-expression',
  'micromark-factory-space',
  'micromark-factory-title',
  'micromark-factory-whitespace',
  'micromark-util-character',
  'micromark-util-chunked',
  'micromark-util-classify-character',
  'micromark-util-combine-extensions',
  'micromark-util-decode-numeric-character-reference',
  'micromark-util-decode-string',
  'micromark-util-encode',
  'micromark-util-events-to-acorn',
  'micromark-util-html-tag-name',
  'micromark-util-normalize-identifier',
  'micromark-util-resolve-all',
  'micromark-util-sanitize-uri',
  'micromark-util-subtokenize',
  'micromark-util-symbol',
  'micromark-util-types',
  'trim-lines',
  'decode-named-character-reference',
  'character-entities',
  'character-entities-html4',
  'character-entities-legacy',
  'ccount',
  'comma-separated-tokens',
  'space-separated-tokens',
  'property-information',
  'web-namespaces',
  'stringify-entities',
  'longest-streak',
  'zwitch',
].join('|')

module.exports = {
  displayName: 'web',
  preset: '../../jest.preset.js',
  transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nx/react/plugins/jest',
    '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nx/next/babel'] }],
  },
  transformIgnorePatterns: [`/node_modules/(?!(${esmPackages})/)`],
  setupFilesAfterEnv: ['<rootDir>/jest.setupafterenv.ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/apps/web',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '<rootDir>/lib/db/schema\\.ts',
    '<rootDir>/lib/db/migrations/',
    '<rootDir>/lib/types/',
    '<rootDir>/components/GlobalStyles/',
  ],
  moduleNameMapper: {
    'next/font/(.*)': nextFontMock,
    '^@react-pdf/renderer$': '<rootDir>/__mocks__/react-pdf-renderer.tsx',
  },
}
