import { useMemo } from 'react'

import {
  Auth0Icon,
  CSS3Icon,
  ChromeIcon,
  CypressIcon,
  DockerIcon,
  EslintIcon,
  GitIcon,
  GithubIcon,
  GitlabIcon,
  HTML5Icon,
  JavascriptIcon,
  JestIcon,
  JsonIcon,
  MaterialUiIcon,
  MongoDBIcon,
  NextJSIcon,
  NodeJSIcon,
  NpmIcon,
  NxIcon,
  PostgreSqlIcon,
  PrettierIcon,
  ReactJSIcon,
  ReactQueryIcon,
  SentryIcon,
  SpiderManIcon,
  StorybookIcon,
  StyledComponentsIcon,
  TypescriptIcon,
  VSCodeIcon,
  VercelIcon,
  WebpackIcon,
  XataIOIcon,
  YarnIcon,
} from '@sdlgr/assets'

import { AnimatedItemProps } from '@web/components/AnimatedItem/AnimatedItem'

export function useMainPortalItems() {
  const items: AnimatedItemProps[] = useMemo(
    () => [
      { svg: <NodeJSIcon /> },
      { svg: <CSS3Icon />, size: 'S' },
      { svg: <GithubIcon />, size: 'S' },
      { svg: <TypescriptIcon />, size: 'S' },
      { svg: <NextJSIcon /> },
      { svg: <ReactJSIcon /> },
      { svg: <MongoDBIcon />, size: 'S' },
      { svg: <ReactQueryIcon /> },
      { svg: <JestIcon /> },
      { svg: <NxIcon />, size: 'S' },
      { svg: <YarnIcon />, size: 'S' },
      { svg: <XataIOIcon />, size: 'S' },
      { svg: <StyledComponentsIcon /> },
      { svg: <EslintIcon /> },
      { svg: <CypressIcon /> },
      { svg: <PrettierIcon /> },
      { svg: <DockerIcon /> },
      { svg: <HTML5Icon /> },
      { svg: <JavascriptIcon /> },
      { svg: <NpmIcon /> },
      { svg: <GitIcon /> },
      { svg: <ChromeIcon /> },
      { svg: <VSCodeIcon /> },
      { svg: <MaterialUiIcon /> },
      { svg: <PostgreSqlIcon /> },
      { svg: <SentryIcon /> },
      { svg: <StorybookIcon /> },
      { svg: <WebpackIcon /> },
      { svg: <GitlabIcon /> },
      { svg: <JsonIcon /> },
      { svg: <VercelIcon /> },
      { svg: <Auth0Icon /> },
      { svg: <SpiderManIcon /> },
    ],
    []
  )

  return items
}
