name: End-to-end tests
on:
  workflow_call:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN  }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Output Vercel Preview URL
        run: echo "The preview url is -> https://${{ steps.vercel_preview_url.outputs.preview_url }}"
      - uses: UnlyEd/github-action-await-vercel@v1.2.42
        id: await-vercel-preview-ready
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.vercel_preview_url.outputs.preview_url }}
          timeout: 300
      - name: Display deployment status
        run: 'echo The deployment at ${{ fromJson(steps.await-vercel-preview-ready.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel-preview-ready.outputs.deploymentDetails).readyState }}'
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Cypress run
        if: steps.vercel_preview_url.outcome == 'success'
        uses: cypress-io/github-action@v6
        with:
          working-directory: apps/web-e2e
          wait-on: 'https://${{ steps.vercel_preview_url.outputs.preview_url }}'
          config: baseUrl=https://${{ steps.vercel_preview_url.outputs.preview_url }}
