name: Test CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Run tests
        run: |
          yarn
          yarn test:all --coverage
