name: End-to-end tests
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - notest
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: aaimio/vercel-preview-url-action@v2.2.0
        id: vercel_preview_url
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Cypress run
        if: steps.vercel_preview_url.outcome == 'success'
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./app/web-e2e
          command: npm run run
          config: baseUrl=${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
