name: End-to-end tests
on:
  workflow_call:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Output Vercel Preview URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"
      - uses: UnlyEd/github-action-await-vercel@v1 # TODO best practices recommend to use a fixed version instead of @v1 for production usage (i.e: @v1.2.32)
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.vercel_preview_url.outputs.preview_url }} # TODO Replace by the domain you want to test
          timeout: 10 # Wait for 10 seconds before failing
          poll-interval: 10 # Wait for 1 second before each retry
      - name: Display deployment status
        run: 'echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Cypress run
        if: steps.vercel_preview_url.outcome == 'success'
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./app/web-e2e
          command: npm run run
          config: baseUrl=https://${{ steps.vercel_preview_url.outputs.preview_url }}
